### ISSUE TITLE
"./minislate build" concatenation errors

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/minislate#48]
Trying the `build` command presents the following concatenate list error:
```
$ ./minislate build
WARNING Building locally can take more than 15 minutes
It is recommended to use hosted images by running ./minislate init
Building the slate container...
can only concatenate list (not "str") to list
```

**Comment by adamhgriffith-uofu** [comment]
@sthapa I started poking around using Python 3.6.8 in `feature/48_build-concatenation-errors`. I am willing to keep at this but wanted to touch base with you since your familiarity with the code-base far exceeds my own.

Stack:
```
run, subprocess.py:423
run, minislate:79
build_minislate, minislate:368
run_main, minislate:513
<module>, minislate:597
```

New exception:
```
(<class 'TypeError'>, TypeError("__init__() got an unexpected keyword argument 'text'",), <traceback object at 0x7f6fc14757c8>)
```

**Comment by sthapa** [comment]
Should be fixed now, can you verify after getting the commit I just made?

**Comment by adamhgriffith-uofu** [comment]
Testing with that commit still appears to be throwing the `TypeError` from above (using Python 3.6.8). Is it working for you and if so with what version?

**Comment by adamhgriffith-uofu** [comment]
Verified with @sthapa that Python 3.9 should be the new minimum version requirement and deleted `feature/48_build-concatenation-errors` as it contained duplicate concatenation fixes now on `develop`.
